In [27]:
%load_ext autoreload
%autoreload 2

In [1]:
import datetime
import tqdm

print(datetime.datetime.now().isoformat())

2025-06-16T23:35:04.957882

In [2]:
import bioacoustics_model_zoo as bmz

2025-06-16 23:35:20.393134: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-16 23:35:20.411405: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-16 23:35:20.432129: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-16 23:35:20.438730: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-16 23:35:20.455463: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-16 23:35:53.994790: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [3]:
from pathlib import Path

audio = sorted(Path("~/scratch/birdclef/raw/birdclef-2024/train_audio/asbfly").expanduser().glob("*.ogg"))[
    :2
]
audio

[PosixPath('/storage/home/hcoda1/7/acheung46/scratch/birdclef/raw/birdclef-2024/train_audio/asbfly/XC134896.ogg'),
 PosixPath('/storage/home/hcoda1/7/acheung46/scratch/birdclef/raw/birdclef-2024/train_audio/asbfly/XC164848.ogg')]

In [4]:
perch = bmz.list_models()["Perch"]()
perch

/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/tensorflow_hub/__init__.py:61: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:599: UserWarning:
                    This architecture is not listed in opensoundscape.ml.cnn_architectures.ARCH_DICT.
                    It will not be available for loading after saving the model with .save() (unless using pickle=True).
                    To make it re-loadable, define a function that generates the architecture from arguments: (n_classes, n_channels)
                    then use opensoundscape.ml.cnn_architectures.register_architecture() to register the generating function.

                    The function can also set the returned object's .constructor_name to the registered string key in ARCH_DICT
                    to avoid this warning and ensure it is reloaded correctly by opensoundscape.ml.load_model().

                    See opensoundscape.ml.cnn_architectures module for examples of constructor functions

  warnings.warn(
/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:623: UserWarning: Failed to detect expected # input channels of this architecture.Make sure your architecture expects the number of channels equal to `channels` argument 1). Pytorch architectures generally expect 3 channels by default.
  warnings.warn(

Perch(
  (network): MLPClassifier(
    (hidden_layers): Sequential()
    (classifier): Linear(in_features=1280, out_features=10932, bias=True)
  )
  (loss_fn): BCEWithLogitsLoss_hot()
)

In [5]:
birdnet = bmz.list_models()["BirdNET"]()
birdnet

File BirdNET_GLOBAL_6K_V2.4_Labels_af.txt already exists; skipping download.

/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:599: UserWarning:
                    This architecture is not listed in opensoundscape.ml.cnn_architectures.ARCH_DICT.
                    It will not be available for loading after saving the model with .save() (unless using pickle=True).
                    To make it re-loadable, define a function that generates the architecture from arguments: (n_classes, n_channels)
                    then use opensoundscape.ml.cnn_architectures.register_architecture() to register the generating function.

                    The function can also set the returned object's .constructor_name to the registered string key in ARCH_DICT
                    to avoid this warning and ensure it is reloaded correctly by opensoundscape.ml.load_model().

                    See opensoundscape.ml.cnn_architectures module for examples of constructor functions

  warnings.warn(
/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:623: UserWarning: Failed to detect expected # input channels of this architecture.Make sure your architecture expects the number of channels equal to `channels` argument 1). Pytorch architectures generally expect 3 channels by default.
  warnings.warn(

downloading model from URL...
File BirdNET_GLOBAL_6K_V2.4_Model_FP16.tflite already exists; skipping download.

BirdNET(
  (network): MLPClassifier(
    (hidden_layers): Sequential()
    (classifier): Linear(in_features=1024, out_features=6522, bias=True)
  )
  (loss_fn): BCEWithLogitsLoss_hot()
)

In [6]:
# NOTE: there is a warmup period for the model...
birdnet.predict(audio[0:1])
%time _ = birdnet.predict(audio)

  0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

CPU times: user 1.48 s, sys: 4.12 ms, total: 1.49 s
Wall time: 1.54 s

In [7]:
%time _ = birdnet.embed(audio, return_preds=False, clip_step=1)

  0%|          | 0/38 [00:00<?, ?it/s]

CPU times: user 3.86 s, sys: 33.5 ms, total: 3.9 s
Wall time: 3.92 s

In [8]:
# NOTE: there is a warmup period for the model...
perch.predict(audio[0:1])
%time _ = perch.predict(audio)

  0%|          | 0/5 [00:00<?, ?it/s]

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1750131539.825091 2836388 service.cc:146] XLA service 0x5555746a3080 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1750131539.967671 2836388 service.cc:154]   StreamExecutor device (0): Host, Default Version
2025-06-16 23:39:07.049569: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
W0000 00:00:1750131553.808833 2836388 assert_op.cc:38] Ignoring Assert operator jax2tf_infer_fn_/assert_equal_1/Assert/AssertGuard/Assert
I0000 00:00:1750131577.531276 2836388 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

  0%|          | 0/8 [00:00<?, ?it/s]

CPU times: user 11.3 s, sys: 23 ms, total: 11.3 s
Wall time: 10.4 s

In [73]:
from birdclef.kaggle.compile import load_tflite_interpreter, run_perch_tflite
import tensorflow as tf
from contexttimer import Timer

# Path to the TFLite model
perch_tflite_path = Path("~/scratch/birdclef/models/2025/v1/Perch/torch-linear-v1/perch.tflite").expanduser()

# Load the TFLite interpreter
perch_interpreter = load_tflite_interpreter(perch_tflite_path)

# First run to warm up
perch_dataloader = perch.predict_dataloader(audio[0:1])
_ = run_perch_tflite(perch_interpreter, perch_dataloader)

# Measure execution time
def run_perch():
    perch_dataloader = perch.predict_dataloader(audio)
    return run_perch_tflite(perch_interpreter, perch_dataloader)

%time perch_out = run_perch()

2025-06-17 01:15:34.816675: E tensorflow/core/framework/node_def_util.cc:676] NodeDef mentions attribute use_inter_op_parallelism which is not in the op definition: Op<name=Transpose; signature=x:T, perm:Tperm -> y:T; attr=T:type; attr=Tperm:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node Transpose}}

CPU times: user 846 ms, sys: 6.69 ms, total: 852 ms
Wall time: 847 ms

In [43]:
perch_out

                                                                            0     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.042605
                                                   5.0        10.0      0.043925
                                                   10.0       15.0      0.191889
                                                   15.0       20.0      0.078761
                                                   20.0       25.0     -0.008164
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.014053
                                                   5.0        10.0      0.100804
                                                   10.0       15.0      0.064618

                                                                            1     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.141005
                                                   5.0        10.0     -0.158573
                                                   10.0       15.0     -0.165586
                                                   15.0       20.0     -0.127910
                                                   20.0       25.0     -0.166585
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.047585
                                                   5.0        10.0     -0.103619
                                                   10.0       15.0     -0.125703

                                                                            2     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.025648
                                                   5.0        10.0      0.057496
                                                   10.0       15.0      0.032176
                                                   15.0       20.0      0.067172
                                                   20.0       25.0      0.077055
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.023723
                                                   5.0        10.0      0.048283
                                                   10.0       15.0      0.040848

                                                                            3     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.041677
                                                   5.0        10.0      0.006564
                                                   10.0       15.0      0.041329
                                                   15.0       20.0     -0.001162
                                                   20.0       25.0      0.020314
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.023687
                                                   5.0        10.0     -0.017900
                                                   10.0       15.0     -0.039507

                                                                            4     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.219057
                                                   5.0        10.0      0.133760
                                                   10.0       15.0      0.241032
                                                   15.0       20.0      0.362048
                                                   20.0       25.0      0.305957
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.064599
                                                   5.0        10.0     -0.002629
                                                   10.0       15.0     -0.011201

                                                                            5     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.093321
                                                   5.0        10.0     -0.108531
                                                   10.0       15.0     -0.106465
                                                   15.0       20.0      0.020511
                                                   20.0       25.0      0.016012
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.237520
                                                   5.0        10.0      0.131647
                                                   10.0       15.0      0.127931

                                                                            6     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.045296
                                                   5.0        10.0     -0.040390
                                                   10.0       15.0     -0.038477
                                                   15.0       20.0     -0.036518
                                                   20.0       25.0     -0.023858
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.021464
                                                   5.0        10.0     -0.030436
                                                   10.0       15.0     -0.007129

                                                                            7     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.033463
                                                   5.0        10.0     -0.005679
                                                   10.0       15.0      0.001972
                                                   15.0       20.0     -0.015141
                                                   20.0       25.0      0.043862
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.071156
                                                   5.0        10.0      0.043630
                                                   10.0       15.0      0.075738

                                                                            8     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.021493
                                                   5.0        10.0      0.057802
                                                   10.0       15.0      0.024136
                                                   15.0       20.0      0.010027
                                                   20.0       25.0      0.024226
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.058777
                                                   5.0        10.0      0.004665
                                                   10.0       15.0      0.047046

                                                                            9     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.015310
                                                   5.0        10.0     -0.009464
                                                   10.0       15.0     -0.032124
                                                   15.0       20.0      0.004725
                                                   20.0       25.0      0.017723
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.053190
                                                   5.0        10.0      0.058007
                                                   10.0       15.0      0.066508

                                                                        ...  \
file                                               start_time end_time  ...
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       ...
                                                   5.0        10.0      ...
                                                   10.0       15.0      ...
                                                   15.0       20.0      ...
                                                   20.0       25.0      ...
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       ...
                                                   5.0        10.0      ...
                                                   10.0       15.0      ...

                                                                            1270  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.068139
                                                   5.0        10.0     -0.038134
                                                   10.0       15.0     -0.026963
                                                   15.0       20.0     -0.066474
                                                   20.0       25.0     -0.001365
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.035056
                                                   5.0        10.0      0.015901
                                                   10.0       15.0     -0.079636

                                                                            1271  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.003904
                                                   5.0        10.0      0.008686
                                                   10.0       15.0      0.026634
                                                   15.0       20.0      0.027452
                                                   20.0       25.0      0.037094
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.012955
                                                   5.0        10.0      0.050458
                                                   10.0       15.0      0.020278

                                                                            1272  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.050975
                                                   5.0        10.0      0.029846
                                                   10.0       15.0      0.156389
                                                   15.0       20.0      0.094284
                                                   20.0       25.0      0.116067
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.021173
                                                   5.0        10.0     -0.033126
                                                   10.0       15.0     -0.010663

                                                                            1273  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.275301
                                                   5.0        10.0      0.264155
                                                   10.0       15.0      0.152691
                                                   15.0       20.0      0.213098
                                                   20.0       25.0      0.258913
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.084607
                                                   5.0        10.0     -0.049295
                                                   10.0       15.0     -0.075536

                                                                            1274  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.033074
                                                   5.0        10.0     -0.039377
                                                   10.0       15.0     -0.041970
                                                   15.0       20.0     -0.039534
                                                   20.0       25.0     -0.025404
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.076791
                                                   5.0        10.0      0.018714
                                                   10.0       15.0      0.019117

                                                                            1275  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.031940
                                                   5.0        10.0      0.053930
                                                   10.0       15.0      0.035128
                                                   15.0       20.0      0.042525
                                                   20.0       25.0     -0.001547
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.011343
                                                   5.0        10.0      0.047943
                                                   10.0       15.0      0.044853

                                                                            1276  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.258302
                                                   5.0        10.0      0.253043
                                                   10.0       15.0      0.188365
                                                   15.0       20.0      0.188616
                                                   20.0       25.0      0.097353
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.169738
                                                   5.0        10.0      0.053109
                                                   10.0       15.0      0.070455

                                                                            1277  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.064362
                                                   5.0        10.0      0.125121
                                                   10.0       15.0      0.136109
                                                   15.0       20.0      0.044475
                                                   20.0       25.0      0.008992
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.019080
                                                   5.0        10.0      0.016290
                                                   10.0       15.0      0.013334

                                                                            1278  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.141944
                                                   5.0        10.0      0.033679
                                                   10.0       15.0      0.064860
                                                   15.0       20.0     -0.044708
                                                   20.0       25.0      0.075674
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.053530
                                                   5.0        10.0     -0.004038
                                                   10.0       15.0      0.015902

                                                                            1279
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.002607
                                                   5.0        10.0     -0.040570
                                                   10.0       15.0      0.021250
                                                   15.0       20.0      0.046647
                                                   20.0       25.0     -0.023289
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.014084
                                                   5.0        10.0      0.003749
                                                   10.0       15.0     -0.014509

[8 rows x 1280 columns]

In [40]:
perch_out.shape

(8, 1280)

In [10]:
perch_interpreter.get_input_details()

[{'name': 'serving_default_inputs:0',
  'index': 0,
  'shape': array([     1, 160000], dtype=int32),
  'shape_signature': array([    -1, 160000], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [11]:
perch_interpreter.get_output_details()

[{'name': 'StatefulPartitionedCall:2',
  'index': 384,
  'shape': array([  1, 500, 160], dtype=int32),
  'shape_signature': array([ -1, 500, 160], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:0',
  'index': 828,
  'shape': array([   1, 1280], dtype=int32),
  'shape_signature': array([  -1, 1280], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:3',
  'index': 832,
  'shape': array([   1, 2333], dtype=int32),
  'shape_signature': array([  -1, 2333], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:5',
  'index': 836,
  'shape': array([ 1, 41], dtype=int32),
  'shape_signature': array([-1, 41], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:1',
  'index': 834,
  'shape': array([  1, 249], dtype=int32),
  'shape_signature': array([ -1, 249], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:4',
  'index': 830,
  'shape': array([    1, 10932], dtype=int32),
  'shape_signature': array([   -1, 10932], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [58]:
from birdclef.kaggle.compile import load_tflite_interpreter
import tensorflow as tf
from contexttimer import Timer

# Path to the TFLite model
birdnet_tflite_path = Path("~/scratch/birdclef/models/2025/v1/BirdNET/torch-linear-v1/birdnet.tflite").expanduser()

# Load the TFLite interpreter
birdnet_interpreter = load_tflite_interpreter(birdnet_tflite_path)

In [13]:
birdnet_input_details = birdnet_interpreter.get_input_details()
birdnet_output_details = birdnet_interpreter.get_output_details()

In [14]:
birdnet_input_details

[{'name': 'INPUT',
  'index': 0,
  'shape': array([     1, 144000], dtype=int32),
  'shape_signature': array([    -1, 144000], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [15]:
birdnet_output_details

[{'name': 'Identity',
  'index': 546,
  'shape': array([   1, 6522], dtype=int32),
  'shape_signature': array([  -1, 6522], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [ ]:
birdnet_dataloader = birdnet.predict_dataloader(audio[0:1], clip_step=1)

res = []
for batch in birdnet_dataloader:
    birdnet_interpreter.set_tensor(birdnet_input_details[0]['index'], batch[0])
    birdnet_interpreter.invoke()
    output_data = birdnet_interpreter.get_tensor(birdnet_output_details[0]['index'])
    res.append(output_data)

res[0].shape

(1, 6522)

In [60]:
import numpy as np
import pandas as pd

pd.DataFrame(
    data=np.stack(res).squeeze(),
    index=birdnet_dataloader.dataset.dataset.label_df.index,
)

                                                                             0     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       -7.506774
                                                   1.0        4.0       -8.647613
                                                   2.0        5.0       -7.845464
                                                   3.0        6.0       -7.643373
                                                   4.0        7.0       -9.401468
                                                   5.0        8.0       -8.580341
                                                   6.0        9.0      -10.213643
                                                   7.0        10.0      -6.160130
                                                   8.0        11.0     -10.190626
                                                   9.0        12.0     -10.497392
                                                   10.0       13.0     -11.946979
                                                   11.0       14.0      -9.964238
                                                   12.0       15.0      -7.970989
                                                   13.0       16.0      -9.138251
                                                   14.0       17.0     -10.244061
                                                   15.0       18.0      -9.551040
                                                   16.0       19.0      -8.209714
                                                   17.0       20.0      -7.096784
                                                   18.0       21.0     -11.533674
                                                   19.0       22.0     -12.320047
                                                   20.0       23.0     -12.408878
                                                   21.0       24.0     -10.641862
                                                   22.0       25.0     -10.671396
                                                   23.0       26.0     -13.191398
                                                   24.0       27.0     -11.255970

                                                                             1     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0      -12.735567
                                                   1.0        4.0      -14.743239
                                                   2.0        5.0      -11.027521
                                                   3.0        6.0      -11.929975
                                                   4.0        7.0      -13.477317
                                                   5.0        8.0      -15.670010
                                                   6.0        9.0      -15.701523
                                                   7.0        10.0     -10.711525
                                                   8.0        11.0     -13.554422
                                                   9.0        12.0     -15.333166
                                                   10.0       13.0     -15.949151
                                                   11.0       14.0      -9.687764
                                                   12.0       15.0     -10.515049
                                                   13.0       16.0     -12.599579
                                                   14.0       17.0     -14.244036
                                                   15.0       18.0     -13.459959
                                                   16.0       19.0     -10.374965
                                                   17.0       20.0     -11.094476
                                                   18.0       21.0     -15.977875
                                                   19.0       22.0     -18.164089
                                                   20.0       23.0     -16.818794
                                                   21.0       24.0     -12.364521
                                                   22.0       25.0     -10.818952
                                                   23.0       26.0     -14.964862
                                                   24.0       27.0     -13.093720

                                                                             2     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0      -12.128023
                                                   1.0        4.0      -13.028152
                                                   2.0        5.0      -11.189791
                                                   3.0        6.0       -8.389795
                                                   4.0        7.0      -12.229095
                                                   5.0        8.0      -12.322523
                                                   6.0        9.0      -15.211663
                                                   7.0        10.0      -8.762765
                                                   8.0        11.0     -11.613965
                                                   9.0        12.0     -13.933137
                                                   10.0       13.0     -14.997967
                                                   11.0       14.0     -13.085483
                                                   12.0       15.0      -8.456628
                                                   13.0       16.0     -10.927116
                                                   14.0       17.0     -13.501138
                                                   15.0       18.0     -13.131957
                                                   16.0       19.0      -9.725299
                                                   17.0       20.0      -8.728446
                                                   18.0       21.0     -15.127913
                                                   19.0       22.0     -17.408619
                                                   20.0       23.0     -17.808523
                                                   21.0       24.0     -11.565566
                                                   22.0       25.0     -12.689489
                                                   23.0       26.0     -15.764959
                                                   24.0       27.0     -15.837397

                                                                             3     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0      -16.930950
                                                   1.0        4.0      -19.056614
                                                   2.0        5.0      -15.536516
                                                   3.0        6.0      -15.281990
                                                   4.0        7.0      -18.435163
                                                   5.0        8.0      -18.604000
                                                   6.0        9.0      -20.297737
                                                   7.0        10.0     -14.892269
                                                   8.0        11.0     -19.229130
                                                   9.0        12.0     -18.358465
                                                   10.0       13.0     -19.582968
                                                   11.0       14.0     -17.098097
                                                   12.0       15.0     -14.321089
                                                   13.0       16.0     -17.656519
                                                   14.0       17.0     -19.058445
                                                   15.0       18.0     -20.151367
                                                   16.0       19.0     -15.688145
                                                   17.0       20.0     -14.593774
                                                   18.0       21.0     -19.091011
                                                   19.0       22.0     -19.551117
                                                   20.0       23.0     -21.189293
                                                   21.0       24.0     -15.902737
                                                   22.0       25.0     -17.145491
                                                   23.0       26.0     -17.586914
                                                   24.0       27.0     -16.737606

                                                                             4     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0      -13.805272
                                                   1.0        4.0      -15.608301
                                                   2.0        5.0      -14.520165
                                                   3.0        6.0      -12.733093
                                                   4.0        7.0      -15.214635
                                                   5.0        8.0      -15.128756
                                                   6.0        9.0      -14.553562
                                                   7.0        10.0     -11.517381
                                                   8.0        11.0     -13.701893
                                                   9.0        12.0     -13.874509
                                                   10.0       13.0     -14.334085
                                                   11.0       14.0     -13.030610
                                                   12.0       15.0     -10.855314
                                                   13.0       16.0     -12.995243
                                                   14.0       17.0     -14.365133
                                                   15.0       18.0     -14.871013
                                                   16.0       19.0     -10.948875
                                                   17.0       20.0     -10.834539
                                                   18.0       21.0     -13.885983
                                                   19.0       22.0     -15.221941
                                                   20.0       23.0     -15.436558
                                                   21.0       24.0     -11.194267
                                                   22.0       25.0     -13.544940
                                                   23.0       26.0     -13.470846
                                                   24.0       27.0     -14.654111

                                                                             5     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0      -19.388584
                                                   1.0        4.0      -19.267042
                                                   2.0        5.0      -14.487982
                                                   3.0        6.0      -12.844191
                                                   4.0        7.0      -18.343470
                                                   5.0        8.0      -20.586489
                                                   6.0        9.0      -20.120785
                                                   7.0        10.0     -10.900822
                                                   8.0        11.0     -18.589630
                                                   9.0        12.0     -21.126530
                                                   10.0       13.0     -20.756485
                                                   11.0       14.0     -15.953403
                                                   12.0       15.0     -12.116307
                                                   13.0       16.0     -18.668234
                                                   14.0       17.0     -19.931255
                                                   15.0       18.0     -18.818325
                                                   16.0       19.0     -11.130915
                                                   17.0       20.0     -11.790789
                                                   18.0       21.0     -19.411020
                                                   19.0       22.0     -20.300623
                                                   20.0       23.0     -20.069304
                                                   21.0       24.0     -13.258389
                                                   22.0       25.0     -15.061001
                                                   23.0       26.0     -21.015642
                                                   24.0       27.0     -18.333117

                                                                             6     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0      -10.413535
                                                   1.0        4.0      -12.274347
                                                   2.0        5.0      -14.505457
                                                   3.0        6.0       -9.787129
                                                   4.0        7.0      -12.646374
                                                   5.0        8.0      -12.853328
                                                   6.0        9.0      -12.841393
                                                   7.0        10.0     -10.948967
                                                   8.0        11.0     -12.270714
                                                   9.0        12.0     -12.136767
                                                   10.0       13.0     -12.179315
                                                   11.0       14.0     -12.303015
                                                   12.0       15.0     -11.076517
                                                   13.0       16.0     -11.911816
                                                   14.0       17.0     -11.579074
                                                   15.0       18.0     -11.918251
                                                   16.0       19.0      -8.999451
                                                   17.0       20.0      -9.854076
                                                   18.0       21.0     -13.847200
                                                   19.0       22.0     -12.264150
                                                   20.0       23.0     -11.987816
                                                   21.0       24.0     -10.700238
                                                   22.0       25.0     -10.898810
                                                   23.0       26.0     -12.606908
                                                   24.0       27.0     -11.428709

                                                                             7     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       -9.000403
                                                   1.0        4.0      -10.796129
                                                   2.0        5.0      -13.926015
                                                   3.0        6.0       -9.325288
                                                   4.0        7.0      -11.854683
                                                   5.0        8.0      -11.807635
                                                   6.0        9.0      -11.809501
                                                   7.0        10.0      -9.683568
                                                   8.0        11.0     -11.255959
                                                   9.0        12.0     -11.225797
                                                   10.0       13.0     -10.742707
                                                   11.0       14.0     -10.891008
                                                   12.0       15.0     -10.217163
                                                   13.0       16.0     -10.652456
                                                   14.0       17.0     -11.167994
                                                   15.0       18.0     -12.028653
                                                   16.0       19.0      -8.007967
                                                   17.0       20.0      -8.948660
                                                   18.0       21.0     -11.553353
                                                   19.0       22.0     -11.356340
                                                   20.0       23.0     -11.531705
                                                   21.0       24.0     -10.243891
                                                   22.0       25.0      -9.387316
                                                   23.0       26.0     -10.543802
                                                   24.0       27.0      -9.678095

                                                                             8     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0      -12.138130
                                                   1.0        4.0      -14.470306
                                                   2.0        5.0      -15.375502
                                                   3.0        6.0      -11.262164
                                                   4.0        7.0      -13.655437
                                                   5.0        8.0      -14.712980
                                                   6.0        9.0      -14.902547
                                                   7.0        10.0     -11.976962
                                                   8.0        11.0     -13.171911
                                                   9.0        12.0     -14.933390
                                                   10.0       13.0     -15.484709
                                                   11.0       14.0     -14.238117
                                                   12.0       15.0     -12.351036
                                                   13.0       16.0     -12.947651
                                                   14.0       17.0     -13.172425
                                                   15.0       18.0     -13.802409
                                                   16.0       19.0     -10.391072
                                                   17.0       20.0     -11.008699
                                                   18.0       21.0     -14.254045
                                                   19.0       22.0     -14.910800
                                                   20.0       23.0     -14.656120
                                                   21.0       24.0     -11.189312
                                                   22.0       25.0     -11.192102
                                                   23.0       26.0     -13.117631
                                                   24.0       27.0     -13.111893

                                                                             9     \

In [ ]:
from birdclef.kaggle.compile import run_birdnet_tflite

# birdnet_dataloader = birdnet.predict_dataloader(audio[0:1])
# _ = run_birdnet_tflite(birdnet_interpreter, birdnet_dataloader)

def run_birdnet(interpreter, clip_step=None):
    birdnet_dataloader = birdnet.predict_dataloader(audio, clip_step=clip_step)
    return run_birdnet_tflite(interpreter, birdnet_dataloader)

%time _ = run_birdnet(birdnet_interpreter)
%time _ = run_birdnet(birdnet_interpreter, clip_step=1)

CPU times: user 824 ms, sys: 16.5 ms, total: 840 ms
Wall time: 849 ms
CPU times: user 2.24 s, sys: 28.1 ms, total: 2.27 s
Wall time: 2.29 s

In [79]:
birdnet_interpreter_multi = load_tflite_interpreter(birdnet_tflite_path, num_threads=8)

%time _ = run_birdnet(birdnet_interpreter_multi)
%time _ = run_birdnet(birdnet_interpreter_multi, clip_step=1)

CPU times: user 1.66 s, sys: 39.6 ms, total: 1.7 s
Wall time: 770 ms
CPU times: user 3.83 s, sys: 31.8 ms, total: 3.87 s
Wall time: 1.86 s